# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relationship_extractor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relationship_extractor.proto',
  package='com.hronosf.relationship.extractor',
  syntax='proto3',
  serialized_options=b'\n\"com.hronosf.relationship.extractorB!RelationshipExtractorServiceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1crelationship_extractor.proto\x12\"com.hronosf.relationship.extractor\"k\n\x1fRelationshipExtractorRequestDTO\x12H\n\rtextToExtract\x18\x01 \x03(\x0b\x32\x31.com.hronosf.relationship.extractor.TextToExtract\"j\n RelationshipExtractorResponseDTO\x12\x46\n\x0c\x64\x61taToUpdate\x18\x01 \x03(\x0b\x32\x30.com.hronosf.relationship.extractor.DataToUpdate\")\n\rTextToExtract\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"D\n\x0c\x44\x61taToUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0brelationMap\x18\x02 \x01(\t\x12\x13\n\x0bprocessedIn\x18\x03 \x01(\x03\x32\xb8\x01\n\x15RelationshipExtractor\x12\x9e\x01\n\x0f\x65xtractRelation\x12\x43.com.hronosf.relationship.extractor.RelationshipExtractorRequestDTO\x1a\x44.com.hronosf.relationship.extractor.RelationshipExtractorResponseDTO\"\x00\x42I\n\"com.hronosf.relationship.extractorB!RelationshipExtractorServiceProtoP\x01\x62\x06proto3'
)




_RELATIONSHIPEXTRACTORREQUESTDTO = _descriptor.Descriptor(
  name='RelationshipExtractorRequestDTO',
  full_name='com.hronosf.relationship.extractor.RelationshipExtractorRequestDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='textToExtract', full_name='com.hronosf.relationship.extractor.RelationshipExtractorRequestDTO.textToExtract', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=175,
)


_RELATIONSHIPEXTRACTORRESPONSEDTO = _descriptor.Descriptor(
  name='RelationshipExtractorResponseDTO',
  full_name='com.hronosf.relationship.extractor.RelationshipExtractorResponseDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataToUpdate', full_name='com.hronosf.relationship.extractor.RelationshipExtractorResponseDTO.dataToUpdate', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=283,
)


_TEXTTOEXTRACT = _descriptor.Descriptor(
  name='TextToExtract',
  full_name='com.hronosf.relationship.extractor.TextToExtract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.hronosf.relationship.extractor.TextToExtract.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='com.hronosf.relationship.extractor.TextToExtract.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=326,
)


_DATATOUPDATE = _descriptor.Descriptor(
  name='DataToUpdate',
  full_name='com.hronosf.relationship.extractor.DataToUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.hronosf.relationship.extractor.DataToUpdate.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relationMap', full_name='com.hronosf.relationship.extractor.DataToUpdate.relationMap', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processedIn', full_name='com.hronosf.relationship.extractor.DataToUpdate.processedIn', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=396,
)

_RELATIONSHIPEXTRACTORREQUESTDTO.fields_by_name['textToExtract'].message_type = _TEXTTOEXTRACT
_RELATIONSHIPEXTRACTORRESPONSEDTO.fields_by_name['dataToUpdate'].message_type = _DATATOUPDATE
DESCRIPTOR.message_types_by_name['RelationshipExtractorRequestDTO'] = _RELATIONSHIPEXTRACTORREQUESTDTO
DESCRIPTOR.message_types_by_name['RelationshipExtractorResponseDTO'] = _RELATIONSHIPEXTRACTORRESPONSEDTO
DESCRIPTOR.message_types_by_name['TextToExtract'] = _TEXTTOEXTRACT
DESCRIPTOR.message_types_by_name['DataToUpdate'] = _DATATOUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RelationshipExtractorRequestDTO = _reflection.GeneratedProtocolMessageType('RelationshipExtractorRequestDTO', (_message.Message,), {
  'DESCRIPTOR' : _RELATIONSHIPEXTRACTORREQUESTDTO,
  '__module__' : 'relationship_extractor_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.relationship.extractor.RelationshipExtractorRequestDTO)
  })
_sym_db.RegisterMessage(RelationshipExtractorRequestDTO)

RelationshipExtractorResponseDTO = _reflection.GeneratedProtocolMessageType('RelationshipExtractorResponseDTO', (_message.Message,), {
  'DESCRIPTOR' : _RELATIONSHIPEXTRACTORRESPONSEDTO,
  '__module__' : 'relationship_extractor_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.relationship.extractor.RelationshipExtractorResponseDTO)
  })
_sym_db.RegisterMessage(RelationshipExtractorResponseDTO)

TextToExtract = _reflection.GeneratedProtocolMessageType('TextToExtract', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTOEXTRACT,
  '__module__' : 'relationship_extractor_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.relationship.extractor.TextToExtract)
  })
_sym_db.RegisterMessage(TextToExtract)

DataToUpdate = _reflection.GeneratedProtocolMessageType('DataToUpdate', (_message.Message,), {
  'DESCRIPTOR' : _DATATOUPDATE,
  '__module__' : 'relationship_extractor_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.relationship.extractor.DataToUpdate)
  })
_sym_db.RegisterMessage(DataToUpdate)


DESCRIPTOR._options = None

_RELATIONSHIPEXTRACTOR = _descriptor.ServiceDescriptor(
  name='RelationshipExtractor',
  full_name='com.hronosf.relationship.extractor.RelationshipExtractor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=399,
  serialized_end=583,
  methods=[
  _descriptor.MethodDescriptor(
    name='extractRelation',
    full_name='com.hronosf.relationship.extractor.RelationshipExtractor.extractRelation',
    index=0,
    containing_service=None,
    input_type=_RELATIONSHIPEXTRACTORREQUESTDTO,
    output_type=_RELATIONSHIPEXTRACTORRESPONSEDTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RELATIONSHIPEXTRACTOR)

DESCRIPTOR.services_by_name['RelationshipExtractor'] = _RELATIONSHIPEXTRACTOR

# @@protoc_insertion_point(module_scope)
