# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import relationship_extractor_pb2 as relationship__extractor__pb2


class RelationshipExtractorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.extractRelation = channel.unary_unary(
                '/com.hronosf.relationship.extractor.RelationshipExtractor/extractRelation',
                request_serializer=relationship__extractor__pb2.RelationshipExtractorRequestDTO.SerializeToString,
                response_deserializer=relationship__extractor__pb2.RelationshipExtractorResponseDTO.FromString,
                )


class RelationshipExtractorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def extractRelation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelationshipExtractorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'extractRelation': grpc.unary_unary_rpc_method_handler(
                    servicer.extractRelation,
                    request_deserializer=relationship__extractor__pb2.RelationshipExtractorRequestDTO.FromString,
                    response_serializer=relationship__extractor__pb2.RelationshipExtractorResponseDTO.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.hronosf.relationship.extractor.RelationshipExtractor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RelationshipExtractor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def extractRelation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.hronosf.relationship.extractor.RelationshipExtractor/extractRelation',
            relationship__extractor__pb2.RelationshipExtractorRequestDTO.SerializeToString,
            relationship__extractor__pb2.RelationshipExtractorResponseDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
