# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summarizer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='summarizer.proto',
  package='com.hronosf.summarizer',
  syntax='proto3',
  serialized_options=b'\n\026com.hronosf.summarizerB\026SummarizerServiceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10summarizer.proto\x12\x16\x63om.hronosf.summarizer\"W\n\x13SummarizeRequestDTO\x12@\n\x0ftextToSummarize\x18\x01 \x03(\x0b\x32\'.com.hronosf.summarizer.TextToSummarize\"R\n\x14SummarizeResponseDTO\x12:\n\x0c\x64\x61taToUpdate\x18\x01 \x03(\x0b\x32$.com.hronosf.summarizer.DataToUpdate\"+\n\x0fTextToSummarize\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"@\n\x0c\x44\x61taToUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x13\n\x0bprocessedIn\x18\x03 \x01(\x03\x32v\n\nSummarizer\x12h\n\tsummarize\x12+.com.hronosf.summarizer.SummarizeRequestDTO\x1a,.com.hronosf.summarizer.SummarizeResponseDTO\"\x00\x42\x32\n\x16\x63om.hronosf.summarizerB\x16SummarizerServiceProtoP\x01\x62\x06proto3'
)




_SUMMARIZEREQUESTDTO = _descriptor.Descriptor(
  name='SummarizeRequestDTO',
  full_name='com.hronosf.summarizer.SummarizeRequestDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='textToSummarize', full_name='com.hronosf.summarizer.SummarizeRequestDTO.textToSummarize', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=131,
)


_SUMMARIZERESPONSEDTO = _descriptor.Descriptor(
  name='SummarizeResponseDTO',
  full_name='com.hronosf.summarizer.SummarizeResponseDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataToUpdate', full_name='com.hronosf.summarizer.SummarizeResponseDTO.dataToUpdate', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=215,
)


_TEXTTOSUMMARIZE = _descriptor.Descriptor(
  name='TextToSummarize',
  full_name='com.hronosf.summarizer.TextToSummarize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.hronosf.summarizer.TextToSummarize.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='com.hronosf.summarizer.TextToSummarize.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=260,
)


_DATATOUPDATE = _descriptor.Descriptor(
  name='DataToUpdate',
  full_name='com.hronosf.summarizer.DataToUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.hronosf.summarizer.DataToUpdate.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summary', full_name='com.hronosf.summarizer.DataToUpdate.summary', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processedIn', full_name='com.hronosf.summarizer.DataToUpdate.processedIn', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=326,
)

_SUMMARIZEREQUESTDTO.fields_by_name['textToSummarize'].message_type = _TEXTTOSUMMARIZE
_SUMMARIZERESPONSEDTO.fields_by_name['dataToUpdate'].message_type = _DATATOUPDATE
DESCRIPTOR.message_types_by_name['SummarizeRequestDTO'] = _SUMMARIZEREQUESTDTO
DESCRIPTOR.message_types_by_name['SummarizeResponseDTO'] = _SUMMARIZERESPONSEDTO
DESCRIPTOR.message_types_by_name['TextToSummarize'] = _TEXTTOSUMMARIZE
DESCRIPTOR.message_types_by_name['DataToUpdate'] = _DATATOUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SummarizeRequestDTO = _reflection.GeneratedProtocolMessageType('SummarizeRequestDTO', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARIZEREQUESTDTO,
  '__module__' : 'summarizer_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.summarizer.SummarizeRequestDTO)
  })
_sym_db.RegisterMessage(SummarizeRequestDTO)

SummarizeResponseDTO = _reflection.GeneratedProtocolMessageType('SummarizeResponseDTO', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARIZERESPONSEDTO,
  '__module__' : 'summarizer_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.summarizer.SummarizeResponseDTO)
  })
_sym_db.RegisterMessage(SummarizeResponseDTO)

TextToSummarize = _reflection.GeneratedProtocolMessageType('TextToSummarize', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTOSUMMARIZE,
  '__module__' : 'summarizer_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.summarizer.TextToSummarize)
  })
_sym_db.RegisterMessage(TextToSummarize)

DataToUpdate = _reflection.GeneratedProtocolMessageType('DataToUpdate', (_message.Message,), {
  'DESCRIPTOR' : _DATATOUPDATE,
  '__module__' : 'summarizer_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.summarizer.DataToUpdate)
  })
_sym_db.RegisterMessage(DataToUpdate)


DESCRIPTOR._options = None

_SUMMARIZER = _descriptor.ServiceDescriptor(
  name='Summarizer',
  full_name='com.hronosf.summarizer.Summarizer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=328,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='summarize',
    full_name='com.hronosf.summarizer.Summarizer.summarize',
    index=0,
    containing_service=None,
    input_type=_SUMMARIZEREQUESTDTO,
    output_type=_SUMMARIZERESPONSEDTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUMMARIZER)

DESCRIPTOR.services_by_name['Summarizer'] = _SUMMARIZER

# @@protoc_insertion_point(module_scope)
