// source: crawler.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO', null, global);
goog.exportSymbol('proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO', null, global);
goog.exportSymbol('proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO', null, global);
goog.exportSymbol('proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO', null, global);
goog.exportSymbol('proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.repeatedFields_, null);
};
goog.inherits(proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.displayName = 'proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.repeatedFields_, null);
};
goog.inherits(proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.displayName = 'proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.displayName = 'proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.displayName = 'proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.displayName = 'proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    toparseList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO}
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO;
  return proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO}
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addToparse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToparseList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string toParse = 1;
 * @return {!Array<string>}
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.prototype.getToparseList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.prototype.setToparseList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.prototype.addToparse = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsServiceRequestDTO.prototype.clearToparseList = function() {
  return this.setToparseList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accesskey: jspb.Message.getFieldWithDefault(msg, 2, ""),
    toparseList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO}
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO;
  return proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO}
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccesskey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addToparse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAccesskey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getToparseList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional int32 userId = 1;
 * @return {number}
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.setUserid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string accessKey = 2;
 * @return {string}
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.getAccesskey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.setAccesskey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string toParse = 3;
 * @return {!Array<string>}
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.getToparseList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.setToparseList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.addToparse = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingAsUserRequestDTO.prototype.clearToparseList = function() {
  return this.setToparseList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    domaintostatusMap: (f = msg.getDomaintostatusMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO;
  return proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getDomaintostatusMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDomaintostatusMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * map<string, string> domainToStatus = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.prototype.getDomaintostatusMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO} returns this
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatusDTO.prototype.clearDomaintostatusMap = function() {
  this.getDomaintostatusMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO}
 */
proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO;
  return proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO}
 */
proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.GetCrawlerProgressByDomainsRequestDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    domaintoprogresspercentsMap: (f = msg.getDomaintoprogresspercentsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO}
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO;
  return proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO}
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getDomaintoprogresspercentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readDouble, null, "", 0.0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDomaintoprogresspercentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeDouble);
  }
};


/**
 * map<string, double> domainToProgressPercents = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.prototype.getDomaintoprogresspercentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO} returns this
 */
proto.com.hronosf.crawler.controller.CrawlerProgressByDomainsResponseDTO.prototype.clearDomaintoprogresspercentsMap = function() {
  this.getDomaintoprogresspercentsMap().clear();
  return this;};


goog.object.extend(exports, proto.com.hronosf.crawler.controller);
