# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import summarizer_pb2 as summarizer__pb2


class SummarizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.summarize = channel.unary_unary(
                '/com.hronosf.summarizer.Summarizer/summarize',
                request_serializer=summarizer__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=summarizer__pb2.SummarizeResponse.FromString,
                )


class SummarizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummarizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.summarize,
                    request_deserializer=summarizer__pb2.SummarizeRequest.FromString,
                    response_serializer=summarizer__pb2.SummarizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.hronosf.summarizer.Summarizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Summarizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.hronosf.summarizer.Summarizer/summarize',
            summarizer__pb2.SummarizeRequest.SerializeToString,
            summarizer__pb2.SummarizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
