# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summarizer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='summarizer.proto',
  package='com.hronosf.summarizer',
  syntax='proto3',
  serialized_options=b'\n\026com.hronosf.summarizerB\026SummarizerServiceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10summarizer.proto\x12\x16\x63om.hronosf.summarizer\"P\n\x10SummarizeRequest\x12<\n\rtextToSummary\x18\x01 \x03(\x0b\x32%.com.hronosf.summarizer.TextToSummary\"Q\n\x11SummarizeResponse\x12<\n\rtextToSummary\x18\x01 \x03(\x0b\x32%.com.hronosf.summarizer.TextToSummary\"O\n\rTextToSummary\x12\n\n\x02id\x18\x01 \x01(\x01\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x13\n\x0bprocessedIn\x18\x04 \x01(\x01\x32p\n\nSummarizer\x12\x62\n\tsummarize\x12(.com.hronosf.summarizer.SummarizeRequest\x1a).com.hronosf.summarizer.SummarizeResponse\"\x00\x42\x32\n\x16\x63om.hronosf.summarizerB\x16SummarizerServiceProtoP\x01\x62\x06proto3'
)




_SUMMARIZEREQUEST = _descriptor.Descriptor(
  name='SummarizeRequest',
  full_name='com.hronosf.summarizer.SummarizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='textToSummary', full_name='com.hronosf.summarizer.SummarizeRequest.textToSummary', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=124,
)


_SUMMARIZERESPONSE = _descriptor.Descriptor(
  name='SummarizeResponse',
  full_name='com.hronosf.summarizer.SummarizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='textToSummary', full_name='com.hronosf.summarizer.SummarizeResponse.textToSummary', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=207,
)


_TEXTTOSUMMARY = _descriptor.Descriptor(
  name='TextToSummary',
  full_name='com.hronosf.summarizer.TextToSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.hronosf.summarizer.TextToSummary.id', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='com.hronosf.summarizer.TextToSummary.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summary', full_name='com.hronosf.summarizer.TextToSummary.summary', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processedIn', full_name='com.hronosf.summarizer.TextToSummary.processedIn', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=288,
)

_SUMMARIZEREQUEST.fields_by_name['textToSummary'].message_type = _TEXTTOSUMMARY
_SUMMARIZERESPONSE.fields_by_name['textToSummary'].message_type = _TEXTTOSUMMARY
DESCRIPTOR.message_types_by_name['SummarizeRequest'] = _SUMMARIZEREQUEST
DESCRIPTOR.message_types_by_name['SummarizeResponse'] = _SUMMARIZERESPONSE
DESCRIPTOR.message_types_by_name['TextToSummary'] = _TEXTTOSUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SummarizeRequest = _reflection.GeneratedProtocolMessageType('SummarizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARIZEREQUEST,
  '__module__' : 'summarizer_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.summarizer.SummarizeRequest)
  })
_sym_db.RegisterMessage(SummarizeRequest)

SummarizeResponse = _reflection.GeneratedProtocolMessageType('SummarizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARIZERESPONSE,
  '__module__' : 'summarizer_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.summarizer.SummarizeResponse)
  })
_sym_db.RegisterMessage(SummarizeResponse)

TextToSummary = _reflection.GeneratedProtocolMessageType('TextToSummary', (_message.Message,), {
  'DESCRIPTOR' : _TEXTTOSUMMARY,
  '__module__' : 'summarizer_pb2'
  # @@protoc_insertion_point(class_scope:com.hronosf.summarizer.TextToSummary)
  })
_sym_db.RegisterMessage(TextToSummary)


DESCRIPTOR._options = None

_SUMMARIZER = _descriptor.ServiceDescriptor(
  name='Summarizer',
  full_name='com.hronosf.summarizer.Summarizer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=290,
  serialized_end=402,
  methods=[
  _descriptor.MethodDescriptor(
    name='summarize',
    full_name='com.hronosf.summarizer.Summarizer.summarize',
    index=0,
    containing_service=None,
    input_type=_SUMMARIZEREQUEST,
    output_type=_SUMMARIZERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUMMARIZER)

DESCRIPTOR.services_by_name['Summarizer'] = _SUMMARIZER

# @@protoc_insertion_point(module_scope)
