// source: crawler.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.hronosf.crawler.controller.CrawlerJobStatus', null, global);
goog.exportSymbol('proto.com.hronosf.crawler.controller.StartParsingRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hronosf.crawler.controller.StartParsingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hronosf.crawler.controller.StartParsingRequest.repeatedFields_, null);
};
goog.inherits(proto.com.hronosf.crawler.controller.StartParsingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.hronosf.crawler.controller.StartParsingRequest.displayName = 'proto.com.hronosf.crawler.controller.StartParsingRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hronosf.crawler.controller.CrawlerJobStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.hronosf.crawler.controller.CrawlerJobStatus.displayName = 'proto.com.hronosf.crawler.controller.CrawlerJobStatus';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hronosf.crawler.controller.StartParsingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hronosf.crawler.controller.StartParsingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    toparseList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingRequest}
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hronosf.crawler.controller.StartParsingRequest;
  return proto.com.hronosf.crawler.controller.StartParsingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hronosf.crawler.controller.StartParsingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingRequest}
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addToparse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hronosf.crawler.controller.StartParsingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hronosf.crawler.controller.StartParsingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToparseList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string toParse = 1;
 * @return {!Array<string>}
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.prototype.getToparseList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.hronosf.crawler.controller.StartParsingRequest} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.prototype.setToparseList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.hronosf.crawler.controller.StartParsingRequest} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.prototype.addToparse = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.hronosf.crawler.controller.StartParsingRequest} returns this
 */
proto.com.hronosf.crawler.controller.StartParsingRequest.prototype.clearToparseList = function() {
  return this.setToparseList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hronosf.crawler.controller.CrawlerJobStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hronosf.crawler.controller.CrawlerJobStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    domaintostatusMap: (f = msg.getDomaintostatusMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerJobStatus}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hronosf.crawler.controller.CrawlerJobStatus;
  return proto.com.hronosf.crawler.controller.CrawlerJobStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hronosf.crawler.controller.CrawlerJobStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerJobStatus}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getDomaintostatusMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hronosf.crawler.controller.CrawlerJobStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hronosf.crawler.controller.CrawlerJobStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDomaintostatusMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * map<string, string> domainToStatus = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.prototype.getDomaintostatusMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.com.hronosf.crawler.controller.CrawlerJobStatus} returns this
 */
proto.com.hronosf.crawler.controller.CrawlerJobStatus.prototype.clearDomaintostatusMap = function() {
  this.getDomaintostatusMap().clear();
  return this;};


goog.object.extend(exports, proto.com.hronosf.crawler.controller);
